/-
Extract the Mathlib premise corpus that EVERY retrieval arm indexes.

Why this file exists, and why it is Lean rather than Python
-----------------------------------------------------------
The study's central claim is a comparison between retrieval architectures. That comparison is only
valid if every arm ranks over an *identical* premise set — otherwise a difference in corpus coverage
is indistinguishable from a difference in retrieval quality. So the corpus is extracted once, here,
and all of BM25 / ProofLens-SV / ProofLens-LI index that one file.

The obvious cheap alternative is to regex `theorem`/`lemma` out of Mathlib's `.lean` sources. It is
wrong in ways that are hard to see afterwards: it misses declarations produced by macros
(`@[simp] lemma` variants, `to_additive` duplicates — which is thousands of real, retrievable
lemmas), it cannot resolve `variable` binders into the statement, and it reproduces source text
rather than the elaborated type. Reading the environment gives the type the prover actually sees.

Run it with `scripts/extract_premises.sh`, which handles the Lean project plumbing.

Determinism note
----------------
Pretty-printing depends on the ambient namespace and `open` declarations, so `Nat.add_comm` could
render differently depending on what this very file imports. The pp call below therefore resets
`currNamespace` and `openDecls`, making the corpus a function of the Mathlib version alone.

Environment variables:
  PREMISE_OUT    output path (default: premises.jsonl)
  PREMISE_LIMIT  stop after N kept declarations — for smoke-testing the pipeline in seconds
                 instead of discovering a format bug after a 15-minute full run
-/
import Mathlib
import Lean

namespace ProofLensExtract

open Lean Meta Elab Command

/-- Name components that only ever appear in compiler-generated declarations. These are not
premises: no human proof cites `Foo.noConfusionType`, and including them would inflate the corpus
with tens of thousands of entries that dilute every retriever's ranking equally but pointlessly. -/
def autoComponents : List String :=
  [ "rec", "recOn", "casesOn", "brecOn", "below", "ibelow", "binductionOn"
  , "ndrec", "ndrecOn", "noConfusion", "noConfusionType", "injEq", "inj"
  , "sizeOf_spec", "sizeOf_inst", "toCtorIdx", "ofNat_toCtorIdx", "ctorIdx"
  , "eq_def", "eq_unfold", "induct", "fun_cases", "match_def", "sizeOf_eq" ]

/-- True for `eq_1`, `proof_3`, `match_2` — auto-generated equation/proof/match lemmas.

Deliberately a *numbered* pattern rather than a prefix test: `eq_` and `match_` are legitimate
prefixes of real lemma names (`Nat.eq_zero_of_le_zero`, `Finset.match_empty`), so excluding on the
prefix alone would quietly delete real premises from the corpus. -/
def isNumbered (pre s : String) : Bool :=
  s.startsWith pre &&
    (let rest := s.drop pre.length
     !rest.isEmpty && rest.all Char.isDigit)

def isAutoComponent (s : String) : Bool :=
  autoComponents.contains s
    || s.startsWith "_"
    || isNumbered "eq_" s
    || isNumbered "proof_" s
    || isNumbered "match_" s

/-- The string components of a name, outermost first. -/
partial def components : Name → List String
  | .str p s => s :: components p
  | .num p _ => "_num" :: components p
  | .anonymous => []

def isAutoGenerated (n : Name) : Bool :=
  n.hasMacroScopes || n.isInternal || (components n).any isAutoComponent

def kindOf : ConstantInfo → String
  | .axiomInfo _  => "axiom"
  | .defnInfo _   => "def"
  | .thmInfo _    => "theorem"
  | .opaqueInfo _ => "opaque"
  | .quotInfo _   => "quot"
  | .inductInfo _ => "inductive"
  | .ctorInfo _   => "ctor"
  | .recInfo _    => "rec"

/-- Kinds carrying no retrievable content: recursors are auto-generated, `Quot` primitives are
four constants nobody cites by name. -/
def skipKind (k : String) : Bool := k == "rec" || k == "quot"

/-- Pretty-print independently of this file's imports and `open`s (see the determinism note). -/
def ppTypeString (e : Expr) : MetaM String :=
  withTheReader Core.Context
    (fun ctx => { ctx with currNamespace := Name.anonymous, openDecls := [] }) do
    let f ← ppExpr e
    return f.pretty (width := 120)

end ProofLensExtract

-- `maxHeartbeats 0` = unlimited. Heartbeats are a *cumulative* budget for the whole elaboration,
-- and the default 200000 is sized for a single tactic block, not for a loop over a million
-- declarations — it aborted at 25k scanned. This is not a case of an individual declaration being
-- pathological, so raising the limit is the correct fix rather than masking a real hang.
set_option maxHeartbeats 0 in
set_option maxRecDepth 10000 in
open Lean Meta Elab Command ProofLensExtract in
run_cmd liftTermElabM do
  let out  := (← IO.getEnv "PREMISE_OUT").getD "premises.jsonl"
  let limit := ((← IO.getEnv "PREMISE_LIMIT").bind String.toNat?).getD 0
  let env ← getEnv

  -- Snapshot the names first: the fold is cheap, and iterating an Array keeps the ordering stable
  -- across runs, which matters because the corpus file is an input to every downstream index.
  let names := env.constants.fold (init := #[]) fun acc n _ => acc.push n
  IO.eprintln s!"[extract] {names.size} constants in the environment (limit={limit})"

  -- NOT `IO.FS.withFile`: its callback is typed `Handle → IO α`, which would force the loop body
  -- into `IO` and make every `MetaM` call below (`ppExpr`, `isProp`) a type error. Opening the
  -- handle directly keeps the loop in `TermElabM`, where IO actions still lift automatically.
  let h ← IO.FS.Handle.mk out IO.FS.Mode.write

  let mut kept := 0
  let mut skipped := 0
  let mut failed := 0
  let mut scanned := 0
  for n in names do
    scanned := scanned + 1
    -- Progress goes to stderr unbuffered. A silent 15-minute run is indistinguishable from a
    -- hang, and that ambiguity has already cost this project a wasted half hour.
    if scanned % 25000 == 0 then
      IO.eprintln s!"[extract] scanned {scanned}/{names.size} — kept {kept}, skipped {skipped}"
    if limit != 0 && kept >= limit then
      break
    if isAutoGenerated n then
      skipped := skipped + 1
      continue
    let some info := env.find? n | continue
    let kind := kindOf info
    if skipKind kind then
      skipped := skipped + 1
      continue
    -- A single un-printable declaration must not abort a 15-minute extraction.
    let stmt? ← try pure (some (← ppTypeString info.type)) catch _ => pure none
    match stmt? with
    | none => failed := failed + 1
    | some stmt =>
      -- A theorem's type IS its proposition, so `isProp` is known without asking. Worth
      -- special-casing: theorems are ~70% of the corpus and `isProp` runs `whnf`, which is by far
      -- the most expensive thing in this loop.
      let isP ← match info with
        | .thmInfo _ => pure true
        | _ => try isProp info.type catch _ => pure false
      let mod := ((env.getModuleFor? n).map toString).getD ""
      let j := Json.mkObj
        [ ("name",      Json.str n.toString)
        , ("kind",      Json.str kind)
        , ("statement", Json.str stmt)
        , ("module",    Json.str mod)
        , ("is_prop",   Json.bool isP) ]
      h.putStrLn j.compress
      kept := kept + 1
  h.flush
  IO.eprintln s!"[extract] DONE kept={kept} skipped={skipped} pp_failed={failed} -> {out}"
